// Auto-generated component keywords for @voyo/docs-db
// question: component name + Chinese + English keywords for matching
export const tips = [
  { name: 'GvAnchor', question: 'GvAnchor 锚点 anchor 跳转 滚动定位 目录 页面内导航' },
  { name: 'GvBacktop', question: 'GvBacktop 回到顶部 backtop 返回顶部 滚动 置顶' },
  { name: 'GvBadge', question: 'GvBadge 徽章 badge 标记 数字 角标 状态 红点' },
  { name: 'GvBodyDialog', question: 'GvBodyDialog 对话框 bodyDialog 弹窗 模态框 确认 嵌套' },
  { name: 'GvBreadCrumb', question: 'GvBreadCrumb 面包屑 breadCrumb 路径 导航 层级 当前位置' },
  { name: 'GvButton', question: 'GvButton 按钮 button 提交 操作 点击 图标 加载' },
  { name: 'GvCard', question: 'GvCard 卡片 card 展示 信息 容器 阴影 页脚' },
  { name: 'GvCascader', question: 'GvCascader 级联选择器 cascader 多级 层级 地区 分类' },
  { name: 'GvCheckbox', question: 'GvCheckbox 复选框 checkbox 多选 勾选 状态 全选' },
  { name: 'GvCheckboxButton', question: 'GvCheckboxButton 复选按钮 checkboxButton 按钮样式 多选 组合 选项' },
  { name: 'GvCheckboxGroup', question: 'GvCheckboxGroup 复选框组 checkboxGroup 多选 数组 批量 选项组' },
  { name: 'GvCol', question: 'GvCol 列 col 栅格 布局 分栏 响应式 偏移 GvRow' },
  { name: 'GvCrud', question: 'GvCrud 增删改查 crud 表格 表单 查询 保存 更新 删除 工具函数' },
  { name: 'GvDatePicker', question: 'GvDatePicker 日期 date 选择 picker 时间 日期选择器' },
  { name: 'GvDialog', question: 'GvDialog 对话框 dialog 弹窗 modal 模态框 确认 提示' },
  { name: 'GvDivider', question: 'GvDivider 分割线 divider 分隔 分隔线 区域划分' },
  { name: 'GvDrawer', question: 'GvDrawer 抽屉 drawer 侧边栏 滑出 展开 浮动面板' },
  { name: 'GvExpandMenu', question: 'GvExpandMenu 展开菜单 expand menu 折叠 导航 菜单栏' },
  { name: 'GvExportDialog', question: 'GvExportDialog 导出 export dialog 导出弹窗 数据导出 下载' },
  { name: 'GvForm', question: 'GvForm 表单 form 输入 提交 编辑 数据录入 查询' },
  { name: 'GvHamburger', question: 'GvHamburger 汉堡菜单 hamburger 侧边栏 折叠 菜单切换' },
  { name: 'GvIcon', question: 'GvIcon 图标 icon iconfont el svg 图标名称' },
  { name: 'GvInput', question: 'GvInput 输入框 input 文本 密码 文本域 textarea' },
  { name: 'GvInputNumber', question: 'GvInputNumber 数字输入框 inputnumber 数字 步进 范围 精度' },
  { name: 'GvLangSelect', question: 'GvLangSelect 语言选择 langselect 国际化 语言切换 i18n' },
  { name: 'GvPopconfirm', question: 'GvPopconfirm 气泡确认 popconfirm 确认 删除 危险操作' },
  { name: 'GvPopover', question: 'GvPopover 弹出框 popover 气泡 提示 悬浮 内容展示' },
  { name: 'GvRadio', question: 'GvRadio 单选框 radio 单项选择 选项 切换' },
  { name: 'GvRadioButton', question: 'GvRadioButton 单选按钮 radio button 按钮样式 组合 选项' },
  { name: 'GvRadioGroup', question: 'GvRadioGroup 单选框组 radio group 互斥选项 选项组 选择' },
  { name: 'GvRow', question: 'GvRow 行组件 row 布局 列 栅格 间距' },
  { name: 'GvScreenFull', question: 'GvScreenFull 全屏 screen full 全屏显示 屏幕 展开' },
  { name: 'GvScrollPane', question: 'GvScrollPane 滚动面板 scroll pane 滚动 内容 容器' },
  { name: 'GvSearchBar', question: 'GvSearchBar 搜索栏 search bar 搜索 筛选 列表查询' },
  { name: 'GvSelect', question: 'GvSelect 选择器 select 下拉 字典 选项 多选' },
  { name: 'GvSidebar', question: 'GvSidebar 侧边栏 sidebar 导航 菜单 布局' },
  { name: 'GvSidebarLogo', question: 'GvSidebarLogo 侧边栏Logo sidebar logo 品牌 标识 导航头' },
  { name: 'GvStep', question: 'GvStep 步骤 step 步骤条 流程 引导' },
  { name: 'GvSteps', question: 'GvSteps 步骤 steps 步骤条 流程 导航' },
  { name: 'GvSwitch', question: 'GvSwitch 开关 switch 切换 状态 列render' },
  { name: 'GvTabPane', question: 'GvTabPane 标签页 tabpane 选项卡 内容 面板' },
  { name: 'GvTable', question: 'GvTable 表格 table 数据 列表 排序 筛选' },
  { name: 'GvTableBar', question: 'GvTableBar 表格工具栏 tablebar 工具 操作 栏' },
  { name: 'GvTabs', question: 'GvTabs 选项卡 tabs 标签页 切换 面板' },
  { name: 'GvTag', question: 'GvTag 标签 tag 标记 分类 状态' },
  { name: 'GvTagsView', question: 'GvTagsView 标签视图 tagsview 多标签 导航 历史' },
  { name: 'GvTheme', question: 'GvTheme 主题 theme 皮肤 样式 换肤' },
  { name: 'GvTimePicker', question: 'GvTimePicker 时间选择 timepicker 时间 选择 表单' },
  { name: 'GvTimeline', question: 'GvTimeline 时间线 timeline 时间轴 流程 记录' },
  { name: 'GvTimelineItem', question: 'GvTimelineItem 时间项 timelineitem 节点 时间线 事件' },
  { name: 'GvTree', question: 'GvTree 树形 tree 层级 展开 折叠' },
  { name: 'GvUpload', question: 'GvUpload 上传 upload 文件 导入 附件' },
  { name: 'GvValidate', question: 'GvValidate 校验 validate 表单 验证 规则' },
];
